var x = 5.3;
var y = 3.5;
var a = 16;
var b = 25;
var name = "Tran Tien Dung";
var description = "siêu đẹp zai";
var troiMua = true;
var troiNang = false;
console.log(a + b);
console.log(a - b);
console.log(a * b);
console.log(a / b);
console.log(a % b);
console.log(x + y);
console.log(x - y);
console.log(x * y);
console.log(x / y);
