var x = 5.3;
var y = 3.5;
var a = 16;
var b = 25;
var name = "Tran Tien Dung";
var description = "siêu đẹp zai";
var troiMua = true;
var troiNang = false;
const AGE = 10;
const CAR = 11;
const TEAM = 12;
const FAMILY = 13;
console.log(a + b);
console.log(a - b);
console.log(a * b);
console.log(a / b);
console.log(a % b);
console.log(x + y);
console.log(x - y);
console.log(x * y);
console.log(x / y);
var c = 'TTD';
var d = "đz vcl";
var z = c + ' ' + d;
console.log(z);
var d = 50;
var e = d;
console.log(e);

